version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=task_2
    ports:
      - "5432:5432"
